language: python
python: 3.7

git:
  depth: 3

cache: pip

env:
    global:
        - HTML=dirhtml

install:
  # python
  - pip install -r requirements.txt

script:
  - make ${HTML}

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: _build/${HTML}
  on:
    branch: master
